# Site settings
name: Chi-An Wei
title: Chi-An Wei | Software Engineer
description: Pursuing researches relating to Robotics, AI, NLP, and Data Mining fields.
url: https://hello.chianwei.xyz/
baseurl: ''
email: kevinwei3@gmail.com
cover: https://hello.chianwei.xyz/img/og.png
logo: https://hello.chianwei.xyz/img/emojis/technologist.png
resume: https://hello.chianwei.xyz/resume.pdf
social:
  - title: email
    url: mailto:kevinwei3@gmail.com
  - title: twitter
    url: https://twitter.com/kevinsmilehehe
  # - title: instagram
  #   url: 
  # - title: codepen
  #   url: 
  - title: facebook
    url: https://www.facebook.com/kevin.wei.982
  - title: youtube
    url: https://www.youtube.com/channel/UCdw2hhnOxPQqFOE-vgODfsQ
  - title: github
    url: https://github.com/chianwei
  - title: linkedin
    url: https://www.linkedin.com/in/chi-an-kevin-wei-077520141

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
